name: Build Everything TGW

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag of llama-cpp-python to build: v0.2.14'
        default: 'v0.2.14'
        required: true
        type: string

permissions:
  contents: write

jobs:          
  build_textgen_wheels_windows:
    name: CUDA Wheels Windows
    uses: ./.github/workflows/build-wheels-oobabooga.yml
    with:
      version: ${{ inputs.version }}
      config: 'os:windows-latest'

  sleep_1:
    name: Sleep for 15 minutes
    needs: build_textgen_wheels_windows
    runs-on: self-hosted
    steps:
      - name: Sleep for 1 hour
        run: sleep 1800

  build_textgen_wheels_linux:
    name: CUDA Wheels Linux
    needs: sleep_1
    uses: ./.github/workflows/build-wheels-oobabooga.yml
    with:
      version: ${{ inputs.version }}
      config: 'os:self-hosted'

  sleep_2:
    name: Sleep for 15 minutes
    needs: build_textgen_wheels_linux
    runs-on: self-hosted
    steps:
      - name: Sleep for 1 hour
        run: sleep 1800

  build_wheels_tensorcores_windows:
    name: Tensor Core Windows
    needs: sleep_2
    uses: ./.github/workflows/build-wheels-tensorcores.yml
    with:
      version: ${{ inputs.version }}
      config: 'os:windows-latest'
      
  sleep_3:
    name: Sleep for 15 minutes
    needs: build_wheels_tensorcores_windows
    runs-on: self-hosted
    steps:
      - name: Sleep for 1 hour
        run: sleep 1800

  build_wheels_tensorcores_linux:
    name: Tensor Core Linux
    needs: sleep_3
    uses: ./.github/workflows/build-wheels-tensorcores.yml
    with:
      version: ${{ inputs.version }}
      config: 'os:self-hosted'

  sleep_4:
    name: Sleep for 15 minutes
    needs: build_wheels_tensorcores_linux
    runs-on: self-hosted
    steps:
      - name: Sleep for 1 hour
        run: sleep 1800

  build_wheels_cpu:
    name: CPU-only Wheels
    needs: sleep_4
    uses: ./.github/workflows/build-wheels-cpu.yml
    with:
      version: ${{ inputs.version }}
      
  sleep_5:
    name: Sleep for 15 minutes
    needs: build_wheels_cpu
    runs-on: self-hosted
    steps:
      - name: Sleep for 1 hour
        run: sleep 1800

  build_wheels_macos:
    name: MacOS Metal Wheels
    needs: sleep_5
    uses: ./.github/workflows/build-wheels-macos.yml
    with:
      version: ${{ inputs.version }}
      
  sleep_6:
    name: Sleep for 15 minutes
    needs: build_wheels_macos
    runs-on: self-hosted
    steps:
      - name: Sleep for 1 hour
        run: sleep 1800

  build_wheels_rocm:
    name: ROCm Wheels
    needs: sleep_6
    uses: ./.github/workflows/build-wheels-oobabooga-rocm.yml
    with:
      version: ${{ inputs.version }}
